# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ans_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ans_wenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_con', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cho_num', models.CharField(max_length=10)),
                ('cho_con', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_con', models.CharField(max_length=200)),
                ('q_xuhao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_data', models.DateTimeField(auto_now=True, verbose_name='date answered')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wenjuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wj_name', models.CharField(max_length=100)),
                ('wj_date', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.User')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.User'),
        ),
        migrations.AddField(
            model_name='record',
            name='wenjuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Wenjuan'),
        ),
        migrations.AddField(
            model_name='question',
            name='questype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Questype'),
        ),
        migrations.AddField(
            model_name='question',
            name='wenjuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Wenjuan'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Question'),
        ),
        migrations.AddField(
            model_name='ans_wenda',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Question'),
        ),
        migrations.AddField(
            model_name='ans_wenda',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Record'),
        ),
        migrations.AddField(
            model_name='ans_choice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Choice'),
        ),
        migrations.AddField(
            model_name='ans_choice',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA.Record'),
        ),
    ]
