# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0006_remove_university_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
